I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    init python:
  File "game/script.rpy", line 9, in script
    init python:
  File "game/script.rpy", line 14, in <module>
    client.connect(ip_port)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "D:\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 9, in script
    init python:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 9, in script
    init python:
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 14, in <module>
    client.connect(ip_port)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
My Question 1.0
Mon Dec 19 17:31:41 2022
